name: Build App

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  APP_NAME: ${{ github.event.repository.name }}

jobs:
  refs:
    name: Prepare CI Environment
    runs-on: ubuntu-22.04
    outputs:
      sha_short: ${{ steps.refs.outputs.sha_short }}
      short_ref: ${{ steps.refs.outputs.short_ref }}
      version: ${{ steps.refs.outputs.version }}
      new_release: ${{ steps.refs.outputs.new_release }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Semantic Release (Dry Run)
        id: semantic
        if: github.ref == 'refs/heads/main' || github.ref_name == 'alpha'
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: true
          semantic_version: 21
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            conventional-changelog-conventionalcommits@7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set outputs
        id: refs
        run: |
          BRANCH=${GITHUB_REF#refs/*/}
          echo "branch: ${BRANCH}"
          BRANCHTRANSLATED=$(echo ${BRANCH} | tr '/' '_')
          echo "short_ref=${BRANCHTRANSLATED}" >> $GITHUB_OUTPUT

          # Определяем версию
          if [ "${{ steps.semantic.outputs.new_release_published }}" = "true" ]; then
            VERSION=${{ steps.semantic.outputs.new_release_version }}
          else
            VERSION=${BRANCHTRANSLATED}_$(git rev-parse --short=12 HEAD)
          fi

          echo "new_release=${{ steps.semantic.outputs.new_release_published }}" >> $GITHUB_OUTPUT
          echo "sha_short=SHA-$(git rev-parse --short=12 HEAD)" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

  build:
    name: Build for LN882H and BL602
    needs: refs
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: OpenLN882H
            variant: default
            gcc: 10.3-2021.10
          - platform: OpenBL602
            variant: default

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install arm-none-eabi-gcc (for LN882H)
        if: matrix.platform == 'OpenLN882H'
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: ${{ matrix.gcc }}
          path-env-var: ARM_NONE_EABI_GCC_PATH

      - name: Run make build
        run: |
          make APP_VERSION=${{ needs.refs.outputs.version }}${{ matrix.variant != 'default' && '_' || '' }}${{ matrix.variant != 'default' && matrix.variant || '' }} \
               APP_NAME=${{ matrix.platform }} \
               VARIANT="${{ matrix.variant }}" \
               ${{ matrix.platform }}

      - name: Save build assets as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}_${{ needs.refs.outputs.version }}_${{ matrix.platform }}${{ matrix.variant != 'default' && '_' || '' }}${{ matrix.variant != 'default' && matrix.variant || '' }}
          path: |
            output/${{ needs.refs.outputs.version }}${{ matrix.variant != 'default' && '_' || '' }}${{ matrix.variant != 'default' && matrix.variant || '' }}/${{ matrix.platform }}_*.bin
            output/${{ needs.refs.outputs.version }}${{ matrix.variant != 'default' && '_' || '' }}${{ matrix.variant != 'default' && matrix.variant || '' }}/${{ matrix.platform }}_*.img
            output/${{ needs.refs.outputs.version }}${{ matrix.variant != 'default' && '_' || '' }}${{ matrix.variant != 'default' && matrix.variant || '' }}/${{ matrix.platform }}_*.rbl
            output/${{ needs.refs.outputs.version }}${{ matrix.variant != 'default' && '_' || '' }}${{ matrix.variant != 'default' && matrix.variant || '' }}/${{ matrix.platform }}_*.fls
            output/${{ needs.refs.outputs.version }}${{ matrix.variant != 'default' && '_' || '' }}${{ matrix.variant != 'default' && matrix.variant || '' }}/${{ matrix.platform }}_*.ota.img

  merge:
    name: Merge Artifacts for Release
    runs-on: ubuntu-22.04
    needs: [refs, build]
    # Запускается всегда, но финальный релиз (release) будет только если это main или alpha и есть новая версия
    steps:
      - name: Merge Artifacts into single archive
        uses: actions/upload-artifact/merge@v4
        with:
          name: ${{ env.APP_NAME }}_${{ needs.refs.outputs.version }}
          delete-merged: true

  release:
    name: Publish Release and Artifacts
    runs-on: ubuntu-22.04
    needs: [merge, refs]
    if: always() && needs.refs.outputs.new_release == 'true' && (github.ref == 'refs/heads/main' || github.ref_name == 'alpha')
    steps:
      - name: Checkout repository for release commit
        uses: actions/checkout@v4

      - name: Download Merged Artifacts (required for semantic-release plugin)
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.APP_NAME }}_${{ needs.refs.outputs.version }}
          path: output/${{ needs.refs.outputs.version }}

      - name: Run Semantic Release (Final)
        id: semantic_final
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: false
          semantic_version: 21
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            conventional-changelog-conventionalcommits@7

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
